services:
  - type: web
    name: ondfn-license
    env: go
    buildCommand: go build -o app server.go
    startCommand: ./app
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8080"
